// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { serializeParameter } from "../core/parameter-serialization.js";
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

/** Query/header parameters for `labels.create`. */
export interface CreateParams {
  /** header `Idempotency-Key` */
  idempotencyKey: string;
}

export class Labels extends APIResource {

  /**
   * Buy and render a shipping label
   *
   * `POST /v1/labels` (`createLabel`)
   *
   * @example
   * const result = await client.labels.create({
   *   format: "pdf",
   *   page_size: "four_by_six",
   *   shipment_id: "shp_00000000000000000001"
   * }, {
   *   idempotencyKey: "123e4567-e89b-12d3-a456-426614174000"
   * });
   * console.log(result);
   */
  create(body: models.CreateLabelRequest, params: CreateParams, options?: RequestOpts): APIPromise<models.Label> {
    return this._promise<models.Label>(() => {
      this._validateInput("labels.create", { path: {  }, params: params ?? {}, body }, options);
      const headers: Record<string, string> = {};
      if (params.idempotencyKey !== undefined) headers["idempotency-key"] = serializeParameter("Idempotency-Key", params.idempotencyKey, "header", {"style":"simple","explode":false,"allowReserved":false});
      return {
        operation: "labels.create",
        method: "POST",
        path: `/v1/labels`,
        responseContract: this._contract("labels.create", 'response'),
        body,
        ...options,
        headers: { ...headers, ...options?.headers },
      };
    });
  }

  /**
   * Retrieve label metadata and download URL
   *
   * `GET /v1/labels/{label_id}` (`retrieveLabel`)
   *
   * @example
   * const result = await client.labels.retrieve("lbl_00000000000000000000");
   * console.log(result);
   */
  retrieve(labelID: string, options?: RequestOpts): APIPromise<models.Label> {
    return this._promise<models.Label>(() => {
      this._validateInput("labels.retrieve", { path: { labelID }, params: {} }, options);
      return {
        operation: "labels.retrieve",
        method: "GET",
        path: `/v1/labels/${serializeParameter("label_id", labelID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("labels.retrieve", 'response'),
        ...options,
      };
    });
  }
}
