// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

/** Query/header parameters for `labels.create`. */
export interface CreateParams {
  /** header `Idempotency-Key` */
  idempotencyKey: string;
}

export class Labels extends APIResource {

  /**
   * Buy and render a shipping label
   *
   * `POST /v1/labels` (`createLabel`)
   *
   * @example
   * const result = await client.labels.create({
   *   format: "pdf",
   *   page_size: "four_by_six",
   *   shipment_id: "shp_00000000000000000001"
   * }, {
   *   idempotencyKey: "string"
   * });
   * console.log(result);
   */
  create(body: models.CreateLabelRequest, params: CreateParams, options?: RequestOpts): APIPromise<models.Label> {
    const headers: Record<string, string> = {};
    if (params.idempotencyKey !== undefined) headers["idempotency-key"] = String(params.idempotencyKey);
    return this._promise<models.Label>({
      method: "POST",
      path: `/v1/labels`,
      body,
      ...options,
      headers: { ...headers, ...options?.headers },
    });
  }

  /**
   * Retrieve label metadata and download URL
   *
   * `GET /v1/labels/{label_id}` (`retrieveLabel`)
   *
   * @example
   * const result = await client.labels.retrieve("string");
   * console.log(result);
   */
  retrieve(labelID: string, options?: RequestOpts): APIPromise<models.Label> {
    return this._promise<models.Label>({
      method: "GET",
      path: `/v1/labels/${encodeURIComponent(labelID)}`,
      ...options,
    });
  }
}
