// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { CursorPage } from "../core/pagination.js";
import type { PageQueryValue, PageRequest } from "../core/pagination.js";
import { serializeParameter } from "../core/parameter-serialization.js";
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

/** Query/header parameters for `pickups.create`. */
export interface CreateParams {
  /** header `Idempotency-Key` */
  idempotencyKey: string;
}

/** Query/header parameters for `pickups.list`. */
export interface ListParams {
  /** query `cursor` */
  cursor?: string;
  /** query `limit` */
  limit?: number;
  /** query `scheduled_on` */
  scheduledOn?: string;
}

export class Pickups extends APIResource {

  /**
   * Cancel a pickup
   *
   * `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
   *
   * @example
   * await client.pickups.cancel("pku_00000000000000000000");
   */
  cancel(pickupID: string, options?: RequestOpts): APIPromise<void> {
    return this._void(() => {
      this._validateInput("pickups.cancel", { path: { pickupID }, params: {} }, options);
      return {
        operation: "pickups.cancel",
        method: "DELETE",
        path: `/v1/pickups/${serializeParameter("pickup_id", pickupID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("pickups.cancel", 'response'),
        ...options,
      };
    });
  }

  /**
   * Schedule a carrier pickup
   *
   * `POST /v1/pickups` (`createPickup`)
   *
   * @example
   * const result = await client.pickups.create({
   *   address: {
   *     city: "Exampleton",
   *     company: "Northstar Supplies",
   *     country: "ZZ",
   *     line1: "14 Fictional Quay",
   *     line2: "Unit 7",
   *     name: "Rowan Example",
   *     phone: "+00000000000",
   *     postal_code: "EX4 2PL",
   *     region: "Test Province"
   *   },
   *   notes: "string",
   *   shipment_ids: [
   *     "string"
   *   ],
   *   window: {
   *     ends_at: "2026-09-06T12:00:00Z",
   *     starts_at: "2026-09-06T09:00:00Z"
   *   }
   * }, {
   *   idempotencyKey: "123e4567-e89b-12d3-a456-426614174000"
   * });
   * console.log(result);
   */
  create(body: models.CreatePickupRequest, params: CreateParams, options?: RequestOpts): APIPromise<models.Pickup> {
    return this._promise<models.Pickup>(() => {
      this._validateInput("pickups.create", { path: {  }, params: params ?? {}, body }, options);
      const headers: Record<string, string> = {};
      if (params.idempotencyKey !== undefined) headers["idempotency-key"] = serializeParameter("Idempotency-Key", params.idempotencyKey, "header", {"style":"simple","explode":false,"allowReserved":false});
      return {
        operation: "pickups.create",
        method: "POST",
        path: `/v1/pickups`,
        responseContract: this._contract("pickups.create", 'response'),
        body,
        ...options,
        headers: { ...headers, ...options?.headers },
      };
    });
  }

  /**
   * List scheduled pickups
   *
   * `GET /v1/pickups` (`listPickups`)
   *
   * @example
   * for await (const item of await client.pickups.list()) {
   *   console.log(item);
   * }
   *
   * Paginated (`cursor_page`): iterate the returned page with `for await…of` to walk every item.
   */
  async list(params?: ListParams, options?: RequestOpts): Promise<CursorPage<models.Pickup>> {
    this._validateInput("pickups.list", { path: {  }, params: params ?? {} }, options);
    const query: Record<string, PageQueryValue> = {};
    if (params?.cursor !== undefined) query["cursor"] = params.cursor;
    if (params?.limit !== undefined) query["limit"] = params.limit;
    if (params?.scheduledOn !== undefined) query["scheduled_on"] = params.scheduledOn;
    const request: PageRequest = {
      operation: "pickups.list",
      method: "GET",
      url: `/v1/pickups`,
      ...options,
      responseContract: this._contract("pickups.list", 'response'),
      query,
      queryStyles: {"cursor":{"style":"form","explode":true,"allowReserved":false},"limit":{"style":"form","explode":true,"allowReserved":false},"scheduled_on":{"style":"form","explode":true,"allowReserved":false}},
      headers: options?.headers ?? {},
    };
    const first = await this._pager.requestPage(request);
    return new CursorPage<models.Pickup>(this._pager, request, first.body, {
      requestCursor: "query.cursor",
      responseItems: "$.data",
      responseNextCursor: "$.next_cursor",
    });
  }

  /**
   * Retrieve a pickup
   *
   * `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
   *
   * @example
   * const result = await client.pickups.retrieve("pku_00000000000000000000");
   * console.log(result);
   */
  retrieve(pickupID: string, options?: RequestOpts): APIPromise<models.Pickup> {
    return this._promise<models.Pickup>(() => {
      this._validateInput("pickups.retrieve", { path: { pickupID }, params: {} }, options);
      return {
        operation: "pickups.retrieve",
        method: "GET",
        path: `/v1/pickups/${serializeParameter("pickup_id", pickupID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("pickups.retrieve", 'response'),
        ...options,
      };
    });
  }
}
