// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

export class Rates extends APIResource {

  /**
   * Quote available shipping services
   *
   * `POST /v1/rates/quote` (`quoteRates`)
   *
   * @example
   * const result = await client.rates.quote({
   *   parcels: [
   *     {
   *       contents: [
   *         {
   *           customs_code: "610910",
   *           description: "Synthetic cotton shirt",
   *           quantity: 2,
   *           unit_value: {
   *             amount: "12.50",
   *             currency: "XTS"
   *           }
   *         }
   *       ],
   *       height_cm: 12,
   *       length_cm: 30.5,
   *       weight_grams: 1750,
   *       width_cm: 20
   *     }
   *   ],
   *   recipient: {
   *     city: "Exampleton",
   *     company: "Northstar Supplies",
   *     country: "ZZ",
   *     line1: "14 Fictional Quay",
   *     line2: "Unit 7",
   *     name: "Rowan Example",
   *     phone: "+00000000000",
   *     postal_code: "EX4 2PL",
   *     region: "Test Province"
   *   },
   *   sender: {
   *     city: "Exampleton",
   *     company: "Northstar Supplies",
   *     country: "ZZ",
   *     line1: "14 Fictional Quay",
   *     line2: "Unit 7",
   *     name: "Rowan Example",
   *     phone: "+00000000000",
   *     postal_code: "EX4 2PL",
   *     region: "Test Province"
   *   }
   * });
   * console.log(result);
   */
  quote(body: models.RateQuoteRequest, options?: RequestOpts): APIPromise<models.RatesQuoteResponse> {
    return this._promise<models.RatesQuoteResponse>({
      method: "POST",
      path: `/v1/rates/quote`,
      body,
      ...options,
    });
  }
}
