// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { CursorPage } from "../core/pagination.js";
import type { PageQueryValue, PageRequest } from "../core/pagination.js";
import { serializeParameter } from "../core/parameter-serialization.js";
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import type { CoreClient } from "../core/client.js";
import { Events } from "./shipments/events.js";
import { APIResource, type RequestOpts } from "../resource.js";

/** Query/header parameters for `shipments.create`. */
export interface CreateParams {
  /** header `Idempotency-Key` */
  idempotencyKey: string;
}

/** Query/header parameters for `shipments.list`. */
export interface ListParams {
  /** query `cursor` */
  cursor?: string;
  /** query `limit` */
  limit?: number;
  /** query `status` */
  status?: models.ShipmentStatus;
}

export class Shipments extends APIResource {
  readonly events: Events;

  constructor(client: CoreClient) {
    super(client);
    this.events = new Events(this._client);
  }

  /**
   * Cancel a shipment before handoff
   *
   * `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
   *
   * @example
   * await client.shipments.cancel("shp_00000000000000000000");
   */
  cancel(shipmentID: string, options?: RequestOpts): APIPromise<void> {
    return this._void(() => {
      this._validateInput("shipments.cancel", { path: { shipmentID }, params: {} }, options);
      return {
        operation: "shipments.cancel",
        method: "DELETE",
        path: `/v1/shipments/${serializeParameter("shipment_id", shipmentID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("shipments.cancel", 'response'),
        ...options,
      };
    });
  }

  /**
   * Create a shipment
   *
   * `POST /v1/shipments` (`createShipment`)
   *
   * @example
   * const result = await client.shipments.create({
   *   delivery_instructions: "Leave with the synthetic reception desk",
   *   metadata: {
   *     additionalProp1: "string"
   *   },
   *   parcels: [
   *     {
   *       contents: [
   *         {
   *           customs_code: "610910",
   *           description: "Synthetic cotton shirt",
   *           quantity: 2,
   *           unit_value: {
   *             amount: "12.50",
   *             currency: "XTS"
   *           }
   *         }
   *       ],
   *       height_cm: 12,
   *       length_cm: 30.5,
   *       weight_grams: 1750,
   *       width_cm: 20
   *     }
   *   ],
   *   recipient: {
   *     city: "Exampleton",
   *     company: "Northstar Supplies",
   *     country: "ZZ",
   *     line1: "14 Fictional Quay",
   *     line2: "Unit 7",
   *     name: "Rowan Example",
   *     phone: "+00000000000",
   *     postal_code: "EX4 2PL",
   *     region: "Test Province"
   *   },
   *   reference: "synthetic-order-1042",
   *   sender: {
   *     city: "Exampleton",
   *     company: "Northstar Supplies",
   *     country: "ZZ",
   *     line1: "14 Fictional Quay",
   *     line2: "Unit 7",
   *     name: "Rowan Example",
   *     phone: "+00000000000",
   *     postal_code: "EX4 2PL",
   *     region: "Test Province"
   *   },
   *   service: "economy"
   * }, {
   *   idempotencyKey: "123e4567-e89b-12d3-a456-426614174000"
   * });
   * console.log(result);
   */
  create(body: models.CreateShipmentRequest, params: CreateParams, options?: RequestOpts): APIPromise<models.Shipment> {
    return this._promise<models.Shipment>(() => {
      this._validateInput("shipments.create", { path: {  }, params: params ?? {}, body }, options);
      const headers: Record<string, string> = {};
      if (params.idempotencyKey !== undefined) headers["idempotency-key"] = serializeParameter("Idempotency-Key", params.idempotencyKey, "header", {"style":"simple","explode":false,"allowReserved":false});
      return {
        operation: "shipments.create",
        method: "POST",
        path: `/v1/shipments`,
        responseContract: this._contract("shipments.create", 'response'),
        body,
        ...options,
        headers: { ...headers, ...options?.headers },
      };
    });
  }

  /**
   * List shipments
   *
   * `GET /v1/shipments` (`listShipments`)
   *
   * @example
   * for await (const item of await client.shipments.list()) {
   *   console.log(item);
   * }
   *
   * Paginated (`cursor_page`): iterate the returned page with `for await…of` to walk every item.
   */
  async list(params?: ListParams, options?: RequestOpts): Promise<CursorPage<models.Shipment>> {
    this._validateInput("shipments.list", { path: {  }, params: params ?? {} }, options);
    const query: Record<string, PageQueryValue> = {};
    if (params?.cursor !== undefined) query["cursor"] = params.cursor;
    if (params?.limit !== undefined) query["limit"] = params.limit;
    if (params?.status !== undefined) query["status"] = params.status as unknown as PageQueryValue;
    const request: PageRequest = {
      operation: "shipments.list",
      method: "GET",
      url: `/v1/shipments`,
      ...options,
      responseContract: this._contract("shipments.list", 'response'),
      query,
      queryStyles: {"cursor":{"style":"form","explode":true,"allowReserved":false},"limit":{"style":"form","explode":true,"allowReserved":false},"status":{"style":"form","explode":true,"allowReserved":false}},
      headers: options?.headers ?? {},
    };
    const first = await this._pager.requestPage(request);
    return new CursorPage<models.Shipment>(this._pager, request, first.body, {
      requestCursor: "query.cursor",
      responseItems: "$.data",
      responseNextCursor: "$.next_cursor",
    });
  }

  /**
   * Retrieve a shipment
   *
   * `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
   *
   * @example
   * const result = await client.shipments.retrieve("shp_00000000000000000000");
   * console.log(result);
   */
  retrieve(shipmentID: string, options?: RequestOpts): APIPromise<models.Shipment> {
    return this._promise<models.Shipment>(() => {
      this._validateInput("shipments.retrieve", { path: { shipmentID }, params: {} }, options);
      return {
        operation: "shipments.retrieve",
        method: "GET",
        path: `/v1/shipments/${serializeParameter("shipment_id", shipmentID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("shipments.retrieve", 'response'),
        ...options,
      };
    });
  }

  /**
   * Update delivery instructions
   *
   * `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
   *
   * @example
   * const result = await client.shipments.update("shp_00000000000000000000", {
   *   delivery_instructions: "string",
   *   metadata: {
   *     additionalProp1: "string"
   *   }
   * });
   * console.log(result);
   */
  update(shipmentID: string, body: models.UpdateShipmentRequest, options?: RequestOpts): APIPromise<models.Shipment> {
    return this._promise<models.Shipment>(() => {
      this._validateInput("shipments.update", { path: { shipmentID }, params: {}, body }, options);
      return {
        operation: "shipments.update",
        method: "PATCH",
        path: `/v1/shipments/${serializeParameter("shipment_id", shipmentID, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("shipments.update", 'response'),
        body,
        ...options,
      };
    });
  }
}
