// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { serializeParameter } from "../core/parameter-serialization.js";
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

export class Tracking extends APIResource {

  /**
   * Retrieve a public tracking timeline
   *
   * `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
   *
   * @example
   * const result = await client.tracking.retrieve("PE-000000000000");
   * console.log(result);
   */
  retrieve(trackingNumber: string, options?: RequestOpts): APIPromise<models.TrackingTimeline> {
    return this._promise<models.TrackingTimeline>(() => {
      this._validateInput("tracking.retrieve", { path: { trackingNumber }, params: {} }, options);
      return {
        operation: "tracking.retrieve",
        method: "GET",
        path: `/v1/tracking/${serializeParameter("tracking_number", trackingNumber, "path", {"style":"simple","explode":false,"allowReserved":false})}`,
        responseContract: this._contract("tracking.retrieve", 'response'),
        ...options,
      };
    });
  }
}
