// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

export class Tracking extends APIResource {

  /**
   * Retrieve a public tracking timeline
   *
   * `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
   *
   * @example
   * const result = await client.tracking.retrieve("string");
   * console.log(result);
   */
  retrieve(trackingNumber: string, options?: RequestOpts): APIPromise<models.TrackingTimeline> {
    return this._promise<models.TrackingTimeline>({
      method: "GET",
      path: `/v1/tracking/${encodeURIComponent(trackingNumber)}`,
      ...options,
    });
  }
}
