// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { CursorPage } from "../core/pagination.js";
import type { PageQueryValue, PageRequest } from "../core/pagination.js";
import type { APIPromise } from "../core/api-promise.js";
import type * as models from "../models.js";
import { APIResource, type RequestOpts } from "../resource.js";

/** Query/header parameters for `webhook_endpoints.list`. */
export interface ListParams {
  /** query `cursor` */
  cursor?: string;
  /** query `limit` */
  limit?: number;
}

export class WebhookEndpoints extends APIResource {

  /**
   * Register a webhook endpoint
   *
   * `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
   *
   * @example
   * const result = await client.webhookEndpoints.create({
   *   description: "string",
   *   events: [
   *     "pickup.completed"
   *   ],
   *   url: "https://hooks.parcel-events.example/events"
   * });
   * console.log(result);
   */
  create(body: models.CreateWebhookEndpointRequest, options?: RequestOpts): APIPromise<models.WebhookEndpoint> {
    return this._promise<models.WebhookEndpoint>({
      method: "POST",
      path: `/v1/webhook-endpoints`,
      body,
      ...options,
    });
  }

  /**
   * List webhook endpoints
   *
   * `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)
   *
   * @example
   * for await (const item of await client.webhookEndpoints.list()) {
   *   console.log(item);
   * }
   *
   * Paginated (`cursor_page`): iterate the returned page with `for await…of` to walk every item.
   */
  async list(params?: ListParams, options?: RequestOpts): Promise<CursorPage<models.WebhookEndpoint>> {
    const query: Record<string, PageQueryValue> = {};
    if (params?.cursor !== undefined) query["cursor"] = params.cursor;
    if (params?.limit !== undefined) query["limit"] = params.limit;
    const request: PageRequest = {
      method: "GET",
      url: `/v1/webhook-endpoints`,
      query,
      headers: options?.headers ?? {},
    };
    const first = await this._pager.requestPage(request);
    return new CursorPage<models.WebhookEndpoint>(this._pager, request, first.body, {
      requestCursor: "query.cursor",
      responseItems: "$.data",
      responseNextCursor: "$.next_cursor",
    });
  }

  /**
   * Delete a webhook endpoint
   *
   * `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
   *
   * @example
   * await client.webhookEndpoints.remove("string");
   */
  remove(endpointID: string, options?: RequestOpts): APIPromise<void> {
    return this._void({
      method: "DELETE",
      path: `/v1/webhook-endpoints/${encodeURIComponent(endpointID)}`,
      ...options,
    });
  }

  /**
   * Update a webhook endpoint
   *
   * `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
   *
   * @example
   * const result = await client.webhookEndpoints.update("string", {
   *   enabled: true,
   *   events: [
   *     "pickup.completed"
   *   ],
   *   url: "https://example.com"
   * });
   * console.log(result);
   */
  update(endpointID: string, body: models.UpdateWebhookEndpointRequest, options?: RequestOpts): APIPromise<models.WebhookEndpoint> {
    return this._promise<models.WebhookEndpoint>({
      method: "PATCH",
      path: `/v1/webhook-endpoints/${encodeURIComponent(endpointID)}`,
      body,
      ...options,
    });
  }
}
