// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { describe, expect, it } from "vitest";
import ParcelEventsSdk from "../src/index.js";

interface ResponseStep {
  readonly status: number;
  readonly contentType: string | null;
  readonly body: string;
}

interface ErrorStep {
  readonly error: Error;
}

type Step = ResponseStep | ErrorStep;

interface Recorded {
  readonly url: string;
  readonly init: RequestInit;
}

function scriptedFetch(steps: readonly Step[]): {
  fetch: (url: string, init: RequestInit) => Promise<Response>;
  calls: Recorded[];
} {
  const remaining = [...steps];
  const calls: Recorded[] = [];
  return {
    calls,
    fetch: (url, init): Promise<Response> => {
      calls.push({ url, init });
      const step = remaining.shift();
      if (step === undefined) return Promise.reject(new Error("smoke script exhausted"));
      if ("error" in step) return Promise.reject(step.error);
      const headers: Record<string, string> = step.contentType === null ? {} : { "content-type": step.contentType };
      return Promise.resolve(new Response(step.body === "" ? null : step.body, { status: step.status, headers }));
    },
  };
}

describe("generated smoke — one method per resource (mock fetch)", () => {
  it("labels.create", async () => {
    const script = scriptedFetch([{ status: 201, contentType: "application/json", body: "{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.labels.create({
  format: "pdf",
  page_size: "four_by_six",
  shipment_id: "shp_00000000000000000001"
}, {
  idempotencyKey: "string"
}).withResponse();
    expect(unwrapped.status).toBe(201);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("POST");
    expect(result).toEqual({
      download_url: "https://downloads.parcel-events.example/labels/synthetic-label.pdf",
      expires_at: "2026-06-09T00:00:00Z",
      format: "pdf",
      id: "lbl_00000000000000000001",
      object: "label",
      price: {
        amount: "12.50",
        currency: "XTS"
      },
      shipment_id: "shp_00000000000000000001"
    });
  });
  it("pickups.cancel", async () => {
    const script = scriptedFetch([{ status: 204, contentType: null, body: "" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.pickups.cancel("string").withResponse();
    expect(unwrapped.status).toBe(204);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("DELETE");
    expect(result).toBeUndefined();
  });
  it("rates.quote", async () => {
    const script = scriptedFetch([{ status: 200, contentType: "application/json", body: "{\"data\":[{\"amount\":{\"amount\":\"string\",\"currency\":\"string\"},\"carrier\":\"string\",\"estimated_delivery_date\":\"string\",\"expires_at\":\"string\",\"id\":\"string\",\"service\":\"string\"}]}" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.rates.quote({
  parcels: [
    {
      contents: [
        {
          customs_code: "610910",
          description: "Synthetic cotton shirt",
          quantity: 2,
          unit_value: {
            amount: "12.50",
            currency: "XTS"
          }
        }
      ],
      height_cm: 12,
      length_cm: 30.5,
      weight_grams: 1750,
      width_cm: 20
    }
  ],
  recipient: {
    city: "Exampleton",
    company: "Northstar Supplies",
    country: "ZZ",
    line1: "14 Fictional Quay",
    line2: "Unit 7",
    name: "Rowan Example",
    phone: "+00000000000",
    postal_code: "EX4 2PL",
    region: "Test Province"
  },
  sender: {
    city: "Exampleton",
    company: "Northstar Supplies",
    country: "ZZ",
    line1: "14 Fictional Quay",
    line2: "Unit 7",
    name: "Rowan Example",
    phone: "+00000000000",
    postal_code: "EX4 2PL",
    region: "Test Province"
  }
}).withResponse();
    expect(unwrapped.status).toBe(200);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("POST");
    expect(result).toEqual({
      data: [
        {
          amount: {
            amount: "string",
            currency: "string"
          },
          carrier: "string",
          estimated_delivery_date: "string",
          expires_at: "string",
          id: "string",
          service: "string"
        }
      ]
    });
  });
  it("shipments.cancel", async () => {
    const script = scriptedFetch([{ status: 204, contentType: null, body: "" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.shipments.cancel("string").withResponse();
    expect(unwrapped.status).toBe(204);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("DELETE");
    expect(result).toBeUndefined();
  });
  it("shipments.events.list", async () => {
    const script = scriptedFetch([{ status: 200, contentType: "application/json", body: "{\"data\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"has_more\":true,\"next_cursor\":\"string\"}" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const result = await client.shipments.events.list("string");
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("GET");
    expect(Array.isArray(result.items())).toBe(true);
  });
  it("tracking.retrieve", async () => {
    const script = scriptedFetch([{ status: 200, contentType: "application/json", body: "{\"events\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"shipment\":{\"created_at\":\"2026-09-04T08:15:30Z\",\"delivery_instructions\":\"string\",\"id\":\"shp_00000000000000000001\",\"metadata\":{\"additionalProp1\":\"string\"},\"object\":\"shipment\",\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"reference\":\"synthetic-order-1042\",\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"service\":\"economy\",\"status\":\"canceled\",\"tracking_number\":\"PE-000000000001\",\"updated_at\":\"2026-09-04T08:16:12Z\"}}" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.tracking.retrieve("string").withResponse();
    expect(unwrapped.status).toBe(200);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("GET");
    expect(result).toEqual({
      events: [
        {
          id: "evt_00000000000000000001",
          location: {
            city: "Samplehaven",
            country: "ZZ"
          },
          message: "Parcel scanned at synthetic sorting hub",
          object: "tracking_event",
          occurred_at: "2026-09-05T05:40:00Z",
          shipment_id: "shp_00000000000000000001",
          status: "canceled"
        }
      ],
      shipment: {
        created_at: "2026-09-04T08:15:30Z",
        delivery_instructions: "string",
        id: "shp_00000000000000000001",
        metadata: {
          additionalProp1: "string"
        },
        object: "shipment",
        parcels: [
          {
            contents: [
              {
                customs_code: "610910",
                description: "Synthetic cotton shirt",
                quantity: 2,
                unit_value: {
                  amount: "12.50",
                  currency: "XTS"
                }
              }
            ],
            height_cm: 12,
            length_cm: 30.5,
            weight_grams: 1750,
            width_cm: 20
          }
        ],
        recipient: {
          city: "Exampleton",
          company: "Northstar Supplies",
          country: "ZZ",
          line1: "14 Fictional Quay",
          line2: "Unit 7",
          name: "Rowan Example",
          phone: "+00000000000",
          postal_code: "EX4 2PL",
          region: "Test Province"
        },
        reference: "synthetic-order-1042",
        sender: {
          city: "Exampleton",
          company: "Northstar Supplies",
          country: "ZZ",
          line1: "14 Fictional Quay",
          line2: "Unit 7",
          name: "Rowan Example",
          phone: "+00000000000",
          postal_code: "EX4 2PL",
          region: "Test Province"
        },
        service: "economy",
        status: "canceled",
        tracking_number: "PE-000000000001",
        updated_at: "2026-09-04T08:16:12Z"
      }
    });
  });
  it("webhook_endpoints.create", async () => {
    const script = scriptedFetch([{ status: 201, contentType: "application/json", body: "{\"created_at\":\"2026-06-09T00:00:00Z\",\"enabled\":true,\"events\":[\"pickup.completed\"],\"id\":\"whe_00000000000000000001\",\"object\":\"webhook_endpoint\",\"signing_secret_hint\":\"synthetic-key-ending-0000\",\"url\":\"https://hooks.parcel-events.example/events\"}" }]);
    const client = new ParcelEventsSdk({ apiKey: "my-api-key", fetch: script.fetch });
    const unwrapped = await client.webhookEndpoints.create({
  description: "string",
  events: [
    "pickup.completed"
  ],
  url: "https://hooks.parcel-events.example/events"
}).withResponse();
    expect(unwrapped.status).toBe(201);
    const result = unwrapped.data;
    expect(script.calls.length).toBe(1);
    expect(script.calls.at(-1)?.init.method).toBe("POST");
    expect(result).toEqual({
      created_at: "2026-06-09T00:00:00Z",
      enabled: true,
      events: [
        "pickup.completed"
      ],
      id: "whe_00000000000000000001",
      object: "webhook_endpoint",
      signing_secret_hint: "synthetic-key-ending-0000",
      url: "https://hooks.parcel-events.example/events"
    });
  });
});
