// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { CursorPage } from "../../core/pagination.js";
import type { PageQueryValue, PageRequest } from "../../core/pagination.js";
import type * as models from "../../models.js";
import { APIResource, type RequestOpts } from "../../resource.js";

/** Query/header parameters for `shipments.events.list`. */
export interface ListParams {
  /** query `cursor` */
  cursor?: string;
  /** query `limit` */
  limit?: number;
}

export class Events extends APIResource {

  /**
   * List tracking events for a shipment
   *
   * `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)
   *
   * @example
   * for await (const item of await client.shipments.events.list("string")) {
   *   console.log(item);
   * }
   *
   * Paginated (`cursor_page`): iterate the returned page with `for await…of` to walk every item.
   */
  async list(shipmentID: string, params?: ListParams, options?: RequestOpts): Promise<CursorPage<models.TrackingEvent>> {
    const query: Record<string, PageQueryValue> = {};
    if (params?.cursor !== undefined) query["cursor"] = params.cursor;
    if (params?.limit !== undefined) query["limit"] = params.limit;
    const request: PageRequest = {
      method: "GET",
      url: `/v1/shipments/${encodeURIComponent(shipmentID)}/events`,
      query,
      headers: options?.headers ?? {},
    };
    const first = await this._pager.requestPage(request);
    return new CursorPage<models.TrackingEvent>(this._pager, request, first.body, {
      requestCursor: "query.cursor",
      responseItems: "$.data",
      responseNextCursor: "$.next_cursor",
    });
  }
}
