// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
// Run with: npx tsx examples/labels.ts
import ParcelEventsSdk from "@sdkfixturelab260904/parcel-events-sdk";

const client = new ParcelEventsSdk({ apiKey: "my-api-key" });

const result = await client.labels.create({
  format: "pdf",
  page_size: "four_by_six",
  shipment_id: "shp_00000000000000000001"
}, {
  idempotencyKey: "string"
});
console.log(JSON.stringify(result, null, 2));
