// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
// Run with: npx tsx examples/pickups.ts
import ParcelEventsSdk from "@sdkfixturelab260904/parcel-events-sdk";

const client = new ParcelEventsSdk({ apiKey: "my-api-key" });

const result = await client.pickups.cancel("string");
console.log(JSON.stringify(result, null, 2));
