// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
// Run with: npx tsx examples/rates.ts
import ParcelEventsSdk from "@sdkfixturelab260904/parcel-events-sdk";

const client = new ParcelEventsSdk({ apiKey: "my-api-key" });

const result = await client.rates.quote({
  parcels: [
    {
      contents: [
        {
          customs_code: "610910",
          description: "Synthetic cotton shirt",
          quantity: 2,
          unit_value: {
            amount: "12.50",
            currency: "XTS"
          }
        }
      ],
      height_cm: 12,
      length_cm: 30.5,
      weight_grams: 1750,
      width_cm: 20
    }
  ],
  recipient: {
    city: "Exampleton",
    company: "Northstar Supplies",
    country: "ZZ",
    line1: "14 Fictional Quay",
    line2: "Unit 7",
    name: "Rowan Example",
    phone: "+00000000000",
    postal_code: "EX4 2PL",
    region: "Test Province"
  },
  sender: {
    city: "Exampleton",
    company: "Northstar Supplies",
    country: "ZZ",
    line1: "14 Fictional Quay",
    line2: "Unit 7",
    name: "Rowan Example",
    phone: "+00000000000",
    postal_code: "EX4 2PL",
    region: "Test Province"
  }
});
console.log(JSON.stringify(result, null, 2));
