// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
// Run with: npx tsx examples/webhook_endpoints.ts
import ParcelEventsSdk from "@sdkfixturelab260904/parcel-events-sdk";

const client = new ParcelEventsSdk({ apiKey: "my-api-key" });

const result = await client.webhookEndpoints.create({
  description: "string",
  events: [
    "pickup.completed"
  ],
  url: "https://hooks.parcel-events.example/events"
});
console.log(JSON.stringify(result, null, 2));
