// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { definitions } from './definitions.js';
import { requestDefinitions } from './requestDefinitions.js';
import { operations } from './operations.js';
import type { Schema, ValidationContract } from '../core/validation.js';
export function contractFor(operation: string, direction: 'request' | 'response' | 'event'): ValidationContract | undefined {
  const entry = operations[operation] as Record<string, Schema | null> | undefined;
  const schema = entry?.[direction];
  return schema == null ? undefined : { schema, definitions: direction === 'request' ? requestDefinitions : definitions };
}
