// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { part0 } from './requestDefinitions-0.js';
export const requestDefinitions: Record<string, unknown> = { ...part0 };
