// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { APIError, type APIErrorInit } from "./core/errors.js";
import { readBodyPointer } from "./core/pagination.js";
import { statusMatches, type StatusMatcher } from "./core/retries.js";

export * from "./core/errors.js";

/** Configured error class — HTTP 401. */
export class AuthenticationError extends APIError {}

/** Configured error class — HTTP 409. */
export class ConflictError extends APIError {}

/** Configured error class — HTTP 404. */
export class NotFoundError extends APIError {}

/** Configured error class — HTTP 402. */
export class PaymentRequiredError extends APIError {}

/** Configured error class — HTTP 429. */
export class RateLimitError extends APIError {}

/** Configured error class — HTTP 5XX. */
export class ServerError extends APIError {}

/** Configured error class — HTTP 422 when `/type` = "https://parcel-events.example/problems/validation". */
export class ValidationError extends APIError {}

interface ErrorMapEntry {
  readonly ctor: new (init: APIErrorInit) => APIError;
  readonly statuses: readonly StatusMatcher[];
  readonly shape: { readonly pointer: string; readonly equals: string | null } | null;
}

/** The IR's frozen (className-sorted) order — the FIRST matching entry wins. */
const ERROR_MAP: readonly ErrorMapEntry[] = [
  { ctor: AuthenticationError, statuses: [401], shape: null },
  { ctor: ConflictError, statuses: [409], shape: null },
  { ctor: NotFoundError, statuses: [404], shape: null },
  { ctor: PaymentRequiredError, statuses: [402], shape: null },
  { ctor: RateLimitError, statuses: [429], shape: null },
  { ctor: ServerError, statuses: ["5XX"], shape: null },
  { ctor: ValidationError, statuses: [422], shape: { pointer: "$.type", equals: "https://parcel-events.example/problems/validation" } },
];

/** Re-type a kernel `APIError` into the most specific configured class. */
export function remapError(error: unknown): unknown {
  if (!(error instanceof APIError)) return error;
  for (const entry of ERROR_MAP) {
    // `(error as unknown)`: keep TS from narrowing `error` to `never` below.
    if ((error as unknown) instanceof entry.ctor) return error;
    if (!entry.statuses.some((matcher) => statusMatches(error.status, matcher))) continue;
    if (entry.shape !== null) {
      const value = readBodyPointer(error.body, entry.shape.pointer);
      if (entry.shape.equals === null ? value === undefined : value !== entry.shape.equals) continue;
    }
    return new entry.ctor({
      status: error.status,
      headers: error.headers,
      body: error.body,
      message: error.message,
    });
  }
  return error;
}
