// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { CoreClient } from "./core/client.js";
import { apiKeyAuth, bearerAuth, type AuthProvider } from "./core/auth.js";
import type { APIPromise } from "./core/api-promise.js";
import type { CallOptions } from "./core/client.js";
import type { Logger, LogLevel } from "./core/logger.js";
import type { RetryPolicy } from "./core/retries.js";
import type { QueryParamValue } from "./core/serialization.js";
import type { KernelFetch } from "./core/transport.js";
import { Labels } from "./resources/labels.js";
import { Pickups } from "./resources/pickups.js";
import { Rates } from "./resources/rates.js";
import { Shipments } from "./resources/shipments.js";
import { Tracking } from "./resources/tracking.js";
import { WebhookEndpoints } from "./resources/webhook_endpoints.js";

/** Named base URLs (`environments:` / the spec's servers). */
export const environments = {
  production: "https://api.parcel-events.example",
  sandbox: "https://sandbox.parcel-events.example"
} as const;

/** Constructor options for the generated client. */
export interface ClientOptions {
  /** Overrides the selected environment URL. */
  readonly baseUrl?: string;
  /** Named environment (default: "production"). */
  readonly environment?: keyof typeof environments;
  /** API key sent as header `Parcel-API-Key`. Falls back to `PARCEL_EVENTS_API_KEY`. */
  readonly apiKey?: string;
  /** Bearer token (`authorization: Bearer …`). Falls back to `PARCEL_EVENTS_BEARER_TOKEN`. */
  readonly bearerToken?: string;
  /** Injected fetch (defaults to `globalThis.fetch`). */
  readonly fetch?: KernelFetch;
  /** Per-request timeout in ms (default 45000). */
  readonly timeoutMs?: number;
  /** Retry-policy overrides (IR defaults below). */
  readonly retries?: Partial<RetryPolicy>;
  readonly defaultHeaders?: Readonly<Record<string, string>>;
  /** Query parameters sent with every request (a per-call value wins). */
  readonly defaultQuery?: Readonly<Record<string, QueryParamValue>>;
  /** Extra `RequestInit` fields merged into every fetch (a dispatcher, `keepalive`, `cache`, …). */
  readonly fetchOptions?: RequestInit;
  /** Where request logs go (default `console`) and how much (default `warn`; credentials are always redacted). */
  readonly logger?: Logger;
  readonly logLevel?: LogLevel;
}

/** The IR-frozen retry defaults (`retries:` in `doctorine.sdk.yml`). */
const DEFAULT_RETRIES: RetryPolicy = {
  enabled: true,
  maxRetries: 3,
  initialDelayMs: 250,
  maxDelayMs: 8000,
  maxElapsedMs: 60000,
  exponent: 2,
  statusCodes: [
    408,
    409,
    429,
    "5XX"
  ],
  retryConnectionErrors: true
};

function maybe<T>(value: T | undefined, build: (value: T) => AuthProvider): AuthProvider | undefined {
  return value === undefined ? undefined : build(value);
}

function envVar(name: string): string | undefined {
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
  return env?.[name];
}

/** The config's anyOf groups in order — the first fully-satisfied group wins. */
function resolveAuth(options: ClientOptions, _fetchFn: KernelFetch): AuthProvider | undefined {
  const providers: Record<string, AuthProvider | undefined> = {
    "api_key": maybe(options.apiKey ?? envVar("PARCEL_EVENTS_API_KEY"), (key) => apiKeyAuth({ placement: "header", name: "Parcel-API-Key", key })),
    "bearer_token": maybe(options.bearerToken ?? envVar("PARCEL_EVENTS_BEARER_TOKEN"), (token) => bearerAuth(token)),
  };
  {
    const group = [providers["api_key"]];
    if (group.every((provider) => provider !== undefined)) {
      return group[0];
    }
  }
  {
    const group = [providers["bearer_token"]];
    if (group.every((provider) => provider !== undefined)) {
      return group[0];
    }
  }
  return undefined;
}

export class ParcelEventsSdk {
  readonly labels: Labels;
  readonly pickups: Pickups;
  readonly rates: Rates;
  readonly shipments: Shipments;
  readonly tracking: Tracking;
  readonly webhookEndpoints: WebhookEndpoints;
  protected readonly _client: CoreClient;
  private readonly _options: ClientOptions;

  constructor(options: ClientOptions = {}) {
    this._options = options;
    const fetchFn: KernelFetch = options.fetch ?? ((url, init): Promise<Response> => fetch(url, init));
    this._client = new CoreClient({
      baseUrl: options.baseUrl ?? environments[options.environment ?? "production"],
      auth: resolveAuth(options, fetchFn),
      fetch: options.fetch,
      timeoutMs: options.timeoutMs ?? 45000,
      retries: { ...DEFAULT_RETRIES, ...options.retries },
      defaultHeaders: options.defaultHeaders ?? {},
      defaultQuery: options.defaultQuery ?? {},
      fetchOptions: options.fetchOptions,
      logger: options.logger,
      logLevel: options.logLevel,
      sdkName: "sdkfixturelab260904-parcel-events-sdk",
      sdkVersion: "1.0.2+sdk.11623df21a87",
      idempotency: { header: "Idempotency-Key", autoGenerate: true },
    });
    this.labels = new Labels(this._client);
    this.pickups = new Pickups(this._client);
    this.rates = new Rates(this._client);
    this.shipments = new Shipments(this._client);
    this.tracking = new Tracking(this._client);
    this.webhookEndpoints = new WebhookEndpoints(this._client);
  }

  /** A client for one call site: the same credentials, these options merged on top. */
  withOptions(overrides: Partial<ClientOptions>): ParcelEventsSdk {
    return new ParcelEventsSdk({
      ...this._options,
      ...overrides,
      defaultHeaders: { ...this._options.defaultHeaders, ...overrides.defaultHeaders },
      defaultQuery: { ...this._options.defaultQuery, ...overrides.defaultQuery },
      retries: { ...this._options.retries, ...overrides.retries },
    });
  }

  /** GET an endpoint the spec does not describe — the caller types the result. */
  get<T = unknown>(path: string, options: CallOptions = {}): APIPromise<T> {
    return this._client.get<T>(path, options);
  }

  /** POST an endpoint the spec does not describe — the caller types the result. */
  post<T = unknown>(path: string, options: CallOptions = {}): APIPromise<T> {
    return this._client.post<T>(path, options);
  }

  /** PUT an endpoint the spec does not describe — the caller types the result. */
  put<T = unknown>(path: string, options: CallOptions = {}): APIPromise<T> {
    return this._client.put<T>(path, options);
  }

  /** PATCH an endpoint the spec does not describe — the caller types the result. */
  patch<T = unknown>(path: string, options: CallOptions = {}): APIPromise<T> {
    return this._client.patch<T>(path, options);
  }

  /** DELETE an endpoint the spec does not describe — the caller types the result. */
  delete<T = unknown>(path: string, options: CallOptions = {}): APIPromise<T> {
    return this._client.delete<T>(path, options);
  }

  /** `tracking.retrieve` attached to the client root (`$client: true`). */
  retrieve(...args: Parameters<Tracking["retrieve"]>): ReturnType<Tracking["retrieve"]> {
    return this.tracking.retrieve(...args);
  }
}

export default ParcelEventsSdk;

export * from "./models.js";
export { APIConnectionError, APIConnectionTimeoutError, APIError, APIUserAbortError, AuthenticationError, BadRequestError, ConflictError, InternalServerError, NotFoundError, PaymentRequiredError, PermissionDeniedError, RateLimitError, ServerError, UnprocessableEntityError, ValidationError, remapError } from "./errors.js";
export type { APIErrorInit } from "./core/errors.js";
export type { RequestOpts } from "./resource.js";
export { CursorPage } from "./core/pagination.js";
export { WEBHOOK_EVENT_NAMES } from "./webhooks.js";
export type { WebhookEvent, WebhookEventMap, WebhookEventName } from "./webhooks.js";
export type { APIResponse, CallOptions } from "./core/client.js";
export { APIPromise } from "./core/api-promise.js";
export type { WithResponse } from "./core/api-promise.js";
export type { Logger, LogLevel } from "./core/logger.js";
