// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

/** Address — #/components/schemas/Address */
export interface Address {
  city: string;
  company?: string | null;
  country: string;
  line1: string;
  line2?: string | null;
  name: string;
  phone?: string | null;
  postal_code: string;
  region?: string | null;
}

/** CreateLabelRequest — #/components/schemas/CreateLabelRequest */
export interface CreateLabelRequest {
  format: LabelFormat;
  page_size?: "a4" | "letter" | "four_by_six";
  shipment_id: string;
}

/** CreatePickupRequest — #/components/schemas/CreatePickupRequest */
export interface CreatePickupRequest {
  address: Address;
  notes?: string | null;
  shipment_ids: string[];
  window: PickupWindow;
}

/** CreateShipmentRequest — #/components/schemas/CreateShipmentRequest */
export interface CreateShipmentRequest {
  delivery_instructions?: string | null;
  metadata?: Record<string, string>;
  parcels: Parcel[];
  recipient: Address;
  reference: string;
  sender: Address;
  service: "economy" | "express" | "same_day";
}

/** CreateWebhookEndpointRequest — #/components/schemas/CreateWebhookEndpointRequest */
export interface CreateWebhookEndpointRequest {
  description?: string | null;
  events: WebhookEventType[];
  url: string;
}

/** Label — #/components/schemas/Label */
export interface Label {
  download_url: string;
  expires_at: string;
  format: LabelFormat;
  id: string;
  object: "label";
  price: Money;
  shipment_id: string;
}

/** LabelFormat — #/components/schemas/LabelFormat */
export type LabelFormat = "pdf" | "png" | "zpl";

/** Money — #/components/schemas/Money */
export interface Money {
  amount: string;
  currency: string;
}

/** Parcel — #/components/schemas/Parcel */
export interface Parcel {
  contents?: ParcelItem[];
  height_cm: number;
  length_cm: number;
  weight_grams: number;
  width_cm: number;
}

/** ParcelItem — #/components/schemas/ParcelItem */
export interface ParcelItem {
  customs_code?: string | null;
  description: string;
  quantity: number;
  unit_value: Money;
}

/** Pickup — #/components/schemas/Pickup */
export interface Pickup {
  address: Address;
  created_at: string;
  id: string;
  object: "pickup";
  shipment_ids: string[];
  status: "scheduled" | "completed" | "canceled" | "missed";
  window: PickupWindow;
}

/** PickupPage — #/components/schemas/PickupPage */
export interface PickupPage {
  data: Pickup[];
  has_more: boolean;
  next_cursor: string | null;
}

/** PickupWindow — #/components/schemas/PickupWindow */
export interface PickupWindow {
  ends_at: string;
  starts_at: string;
}

/** RateQuote — #/components/schemas/RateQuote */
export interface RateQuote {
  amount: Money;
  carrier: string;
  estimated_delivery_date: string;
  expires_at: string;
  id: string;
  service: string;
}

/** RateQuoteRequest — #/components/schemas/RateQuoteRequest */
export interface RateQuoteRequest {
  parcels: Parcel[];
  recipient: Address;
  sender: Address;
}

/** RatesQuoteResponse — synthesized:RatesQuoteResponse */
export interface RatesQuoteResponse {
  data: RateQuote[];
}

/** Shipment — #/components/schemas/Shipment */
export interface Shipment {
  created_at: string;
  delivery_instructions?: string | null;
  id: string;
  metadata?: Record<string, string>;
  object: "shipment";
  parcels: Parcel[];
  recipient: Address;
  reference: string;
  sender: Address;
  service: "economy" | "express" | "same_day";
  status: ShipmentStatus;
  tracking_number: string;
  updated_at: string;
}

/** ShipmentPage — #/components/schemas/ShipmentPage */
export interface ShipmentPage {
  data: Shipment[];
  has_more: boolean;
  next_cursor: string | null;
}

/** ShipmentStatus — #/components/schemas/ShipmentStatus */
export type ShipmentStatus = "draft" | "label_purchased" | "in_transit" | "out_for_delivery" | "delivered" | "exception" | "canceled";

/** ShipmentStatusEvent — #/components/schemas/ShipmentStatusEvent */
export interface ShipmentStatusEvent {
  created_at: string;
  data: ShipmentStatusEventData;
  id: string;
  type: "shipment.status_changed";
}

/** ShipmentStatusEventData — synthesized:ShipmentStatusEventData */
export interface ShipmentStatusEventData {
  event: TrackingEvent;
  shipment: Shipment;
}

/** TrackingEvent — #/components/schemas/TrackingEvent */
export interface TrackingEvent {
  id: string;
  location: TrackingEventLocation;
  message?: string;
  object: "tracking_event";
  occurred_at: string;
  shipment_id: string;
  status: ShipmentStatus;
}

/** TrackingEventLocation — synthesized:TrackingEventLocation */
export interface TrackingEventLocation {
  city: string;
  country: string;
}

/** TrackingEventPage — #/components/schemas/TrackingEventPage */
export interface TrackingEventPage {
  data: TrackingEvent[];
  has_more: boolean;
  next_cursor: string | null;
}

/** TrackingTimeline — #/components/schemas/TrackingTimeline */
export interface TrackingTimeline {
  events: TrackingEvent[];
  shipment: Shipment;
}

/** UpdateShipmentRequest — #/components/schemas/UpdateShipmentRequest */
export interface UpdateShipmentRequest {
  delivery_instructions?: string | null;
  metadata?: Record<string, string>;
}

/** UpdateWebhookEndpointRequest — #/components/schemas/UpdateWebhookEndpointRequest */
export interface UpdateWebhookEndpointRequest {
  enabled?: boolean;
  events?: WebhookEventType[];
  url?: string;
}

/** WebhookEndpoint — #/components/schemas/WebhookEndpoint */
export interface WebhookEndpoint {
  created_at: string;
  enabled: boolean;
  events: WebhookEventType[];
  id: string;
  object: "webhook_endpoint";
  signing_secret_hint?: string;
  url: string;
}

/** WebhookEndpointPage — #/components/schemas/WebhookEndpointPage */
export interface WebhookEndpointPage {
  data: WebhookEndpoint[];
  has_more: boolean;
  next_cursor: string | null;
}

/** WebhookEventType — #/components/schemas/WebhookEventType */
export type WebhookEventType = "shipment.created" | "shipment.status_changed" | "shipment.delivered" | "shipment.exception" | "pickup.completed";
