// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import { contractFor } from "./contracts/index.js";
import type { ValidationOptions } from "./core/validation.js";
import type { RetryPolicy } from "./core/retries.js";
import type { APIPromise } from "./core/api-promise.js";
import type { APIResponse, CoreClient, RequestOptions } from "./core/client.js";
import type { PageFetcher, PageRequest } from "./core/pagination.js";
import { remapError } from "./errors.js";

/** Per-call request options accepted by every generated method. */
export interface RequestOpts {
  readonly headers?: Readonly<Record<string, string>>;
  readonly timeoutMs?: number;
  readonly signal?: AbortSignal;
  readonly idempotencyKey?: string;
  readonly retries?: Partial<RetryPolicy>;
  readonly validation?: ValidationOptions;
  readonly retryUnsafeRequests?: boolean;
}

/** Base class of every generated resource: kernel access + error remapping. */
export class APIResource {
  protected readonly _pager: PageFetcher;
  protected readonly _contract = contractFor;

  protected _validateInput(operation: string, value: unknown, options?: RequestOpts): void {
    this._client.validateInput(contractFor(operation, 'request'), value, options);
  }

  constructor(protected readonly _client: CoreClient) {
    this._pager = {
      requestPage: async (request: PageRequest): Promise<{ body: unknown }> => {
        try {
          return await this._client.requestPage(request);
        } catch (error) {
          throw remapError(error);
        }
      },
    };
  }

  protected async _request<T>(options: RequestOptions): Promise<APIResponse<T>> {
    try {
      return await this._client.request<T>(options);
    } catch (error) {
      throw remapError(error);
    }
  }

  /** The lazy promise every plain method returns: `await` it, or `.asResponse()` / `.withResponse()`. */
  protected _promise<T>(options: RequestOptions | (() => RequestOptions)): APIPromise<T> {
    return this._client.promise<T>(options, remapError);
  }

  /** A method without a response body: the body is discarded, status + headers stay reachable. */
  protected _void(options: RequestOptions | (() => RequestOptions)): APIPromise<void> {
    return this._client.promise<void>(options, remapError, async (response) => {
      await response.body?.cancel();
    });
  }

  protected async _raw(options: RequestOptions): Promise<Response> {
    try {
      return await this._client.raw(options);
    } catch (error) {
      throw remapError(error);
    }
  }
}
