// Generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.
import * as models from "./models.js";

/**
 * Every webhook event this API can deliver, keyed by its wire event name.
 * Payloads are the raw deserialized JSON — check the delivery’s authenticity per the API’s docs BEFORE trusting it.
 */
export interface WebhookEventMap {
  /** Shipment status changed */
  shipmentStatusChanged: models.ShipmentStatusEvent;
}

/** The wire names of every deliverable webhook event. */
export type WebhookEventName = keyof WebhookEventMap;

/** A decoded inbound webhook delivery, discriminated by `type`. */
export type WebhookEvent = {
  [K in WebhookEventName]: { readonly type: K; readonly payload: WebhookEventMap[K] };
}[WebhookEventName];

/** Every deliverable webhook event name, in spec order. */
export const WEBHOOK_EVENT_NAMES: readonly WebhookEventName[] = [
  "shipmentStatusChanged",
];
